### ISSUE TITLE
In Text Capture create input step, duplicate files are only judged by "Taxon names"

### ISSUE THREAD

**Issue by dongfang91** [biosemantics/etc-site#347] opened 2016-02-23 23:59 UTC
See the image. 
![tc create input error](https://cloud.githubusercontent.com/assets/12636365/13270950/b9be6792-da4e-11e5-970e-cfc69e988fd9.png)

**Comment by hongcui** [comment] 2016-02-24 16:10
I couldn't reproduce the error message. I copied one entry 3 times, and created 3 files with names _1, _2, and _3.

**Comment by hongcui** [comment] 2016-02-24 18:09
Now I hit the error message. It occurs at Create Input step for Text Capture. 

I don't think it is a bug. It is the desired behavior. Taxon names (name + authority + date) should be the unique identifier for a description. The description content should be merged into one description.

**Comment by dongfang91** [comment] 2016-02-25 21:40
Okay, that's what I asked in the meeting, so might show some promt information for the user, ""merge these two input files together".

**Closed** 2016-05-05 18:33 UTC
